<?xml version="1.0"?>
<!DOCTYPE comments [
<!ELEMENT comments (comment*)>
<!ELEMENT comments (id,comment_content, comment_user,comment_time,comment_post)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT comment_post (#PCDATA)>
<!ELEMENT comment_content (#PCDATA)>
<!ELEMENT ipAddr (#PCDATA)>
<!ELEMENT comment_user (#PCDATA)>
<!ELEMENT comment_time (#PCDATA)>
]>
<comments>
    {% for comment in comments %}
        <comment>
            <id>{{comment.id}}</id>
            <comment_content>{{comment.comment_content}}</comment_content>
            <comment_user>{{comment.comment_user}}</comment_user>
            <comment_time>{{comment.comment_time}}</comment_time>
            <comment_post>{{comment.comment_post}}</comment_post>
        </comment>
    {% endfor %}
</comments>